import sys

# >chrI
#CCACACCACACCCACACACCCACACACCACACCACACACCACACCACACC
#CACACACACACATCCTAACACTACCCTAACACAGCCCTAATCTAACCCTG
#GCCAACCTGTCTCTCAACTTACCCTCCATTACCCTGCCTCCACTCGTTAC

from collections import defaultdict

sequence_dict = defaultdict(str)

for line in sys.stdin:
    l1 = line.strip()
    if l1.startswith (">"):
        key = l1
    if not l1.startswith (">"):
        sequence_dict[key] += str(l1)

for key, value in sequence_dict.items(): 
        #print(key + "\n" + value) 
#>chrI
#CCACACCACACCCACACACCCACACACCACACCACACACCACACCACACCCACACACACACATCCTAACACTACCCTAACACAGCCCTAATCTAACCCTGGCCAACCTGTCTCTCAACTTACCCTCCATTACCCTGCCTCCACTCGTTACCCTGTCCCATTCAACCATACCACTCCGAACCACCATCCATCCCTCTACTTACTACCACTCACCCACCGTTACCCTCCAATTACCCATATCCAACCCACTGCCACTTACCCTACCATTACCCTACCATCCACCATGACCTACTCACCATACTGTTCTTCTACCCACCATATTGAAACGCTAACAAATGATCGTAAATAACACACACGTGCTTACCCTACCACTTTATACCACCACCACATGCCATACTCACCCTCACTTGTATACTGATTTTACGTACGCACACGGATGCTACAGTATATA

#make substrings that are 75 bp long and have atleast 3 GC: 

for value in sequence_dict:
    if 'GC' or 'gc' in value:
       substr = 
